[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  GEMINI_API_KEY = "YOUR_GEMINI_API_KEY"
  NEXT_PUBLIC_BNB_WALLET = "0x6F56c0e475BD61904bfedE0d1cA5Ff69b16A4CCd"

[[plugins]]
  package = "@netlify/plugin-nextjs"
